# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: TerraformInstaller@0
  displayName: install
  inputs:
    terraformVersion: '0.14.7'
- task: TerraformTaskV2@2
  displayName: 'init'
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'Azure for Students (3457d5d0-1535-40c6-85fb-cb1919104698)'
    backendAzureRmResourceGroupName: 'prince_rg'
    backendAzureRmStorageAccountName: 'princestorage'
    backendAzureRmContainerName: 'princecontainer'
    backendAzureRmKey: 'terraform.tfstate'
- task: TerraformTaskV2@2
  displayName: 'plan'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'Azure for Students (3457d5d0-1535-40c6-85fb-cb1919104698)'
- task: TerraformTaskV2@2
  displayName: 'apply'
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'Azure for Students (3457d5d0-1535-40c6-85fb-cb1919104698)'
